// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACol: typeof import('ant-design-vue/es')['Col']
    ARow: typeof import('ant-design-vue/es')['Row']
    CompositionD3Bar: typeof import('./src/components/CompositionD3Bar.vue')['default']
    CompositionDatasaurus: typeof import('./src/components/CompositionDatasaurus.vue')['default']
    D3Bar: typeof import('./src/components/d3-bar.vue')['default']
    D3BarOption: typeof import('./src/components/d3-bar-option.vue')['default']
    D3BarOptions: typeof import('./src/components/D3BarOptions.vue')['default']
    Datasaurus: typeof import('./src/components/Datasaurus.vue')['default']
    OptionsD3Bar: typeof import('./src/components/OptionsD3Bar.vue')['default']
    'OptionsD3Bar copy': typeof import('./src/components/OptionsD3Bar copy.vue')['default']
  }
}

export {}
