// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACol: typeof import('ant-design-vue/es')['Col']
    ARow: typeof import('ant-design-vue/es')['Row']
    ASwitch: typeof import('ant-design-vue/es')['Switch']
    D3BarButton: typeof import('./src/components/D3BarButton.vue')['default']
    D3BarComposition: typeof import('./src/components/D3BarComposition.vue')['default']
    D3BarOptions: typeof import('./src/components/D3BarOptions.vue')['default']
    Datasaurus: typeof import('./src/components/Datasaurus.vue')['default']
    DatasaurusLegend: typeof import('./src/components/DatasaurusLegend.vue')['default']
    Netflix: typeof import('./src/components/Netflix.vue')['default']
    SVGdefs: typeof import('./src/components/SVGdefs.vue')['default']
  }
}

export {}
